defaults:
  - _self_
  - data: toronto

paths:
  reports: reports
  figures: ${..paths.reports}/figures
  models: models

train:
  epochs: 50

  fast_dev_run: false
  overfit_batches: 0
  schedule_lr: true
  debug: false

  wandb: true
  wandb_project: activity-graphs
  wandb_entity: luca-bataillard-ucl-university-college-london