files:
  raw_household: Household.parquet
  raw_person: Person.parquet
  raw_trip: Trip.parquet
  raw_stage: Stage.parquet

paths:
  data_processed: data/processed
  data_raw: data/raw
  data_raw_ltds: ${paths.data_raw}/LTDS0515